---
image:
  file: .gitpod.Dockerfile
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - init: ./gradlew build
  - init: java -jar software-challenge-gui-21.3.3-linux.jar
  - command: ./gradlew run
